### PR TITLE
Use html_safe instead of CGI.escapeHtml

### PR DESCRIPTION
**Pull request by ovr**
Hey!

Thanks

### CODE REVIEW

**Comment by ovr** [comment]
ping @joshdholtz Thanks

**Comment by revolter** [comment]
Do you have an example in which the previous code fails? Or a comparison between these APIs?

**Comment by ovr** [comment]
I am going to close PR, due this will not work, but anyway I am having epic strange thing related UTF escape

`Móvil` displayed/converted as `MÃ³vi` looks likes, there is a problem on read by `apktools/apkxml`

I tested escape with CGI and it works correctly:

```
require 'cgi'

puts(CGI.escapeHTML("Móvil Stage"))
```

as `Móvil Stage`

weird...

**Comment by ovr** [comment]
I find an issue inside `apktools ` repository, refs https://github.com/devunwired/apktools/issues/17

**Pull request closed without merging**
