### PR TITLE
Add a method to upload xcode archive to s3

### PR DESCRIPTION
**Pull request by claireAD**
First thank you so much for this plugin, it is so useful!
I need to upload xcode archive instead of .ipa, to be more precise I want to send someone an app he has to re-sign and it is easier to re-sign an archive instead of an .ipa.
I add a method to upload archive provided with parameter :archive, this parameter is optional and do not change other features.

### CODE REVIEW

**Comment by joshdholtz** [comment]
@claireAD This is fantastic! Going to merge this and will get a new version released this week 😊

**Comment by davibe** [comment]
Something like `artifacts: "path/to/folder"` that uploads everything to `[buildName]/[platform]/artifacts` ?

**Comment by davibe** [comment]
an array of files is rather boring as for example if you want to upload a webpage with the changelog + autogenerated pages with test results

**Comment by claireAD** [comment]
Hi @joshdholtz 
do you plan to do a release soon? it would be great if this change could be merged
thanks a lot!

**Comment by acecilia** [comment]
Hi @claireduf:
Just updated from 1.1.1 to 1.4.0, and realized that the archive is being uploaded to S3 without me specifying it in the parameters. 

How can I avoid the upload of the archive? Zipping and uploading it takes considerable time.

Thanks!

**Comment by claireduf** [comment]
Hi @acecilia 
if I add a parameter skip_xcarchive_upload to avoid uploading xcarchive, would it be fine?

**Comment by acecilia** [comment]
@claireduf I would go for:
- Having the `xcarchive` parameter, in order to pass the path to the archive.
- Only upload the archive if the `xcarchive` parameter has been assigned a value.
- Have a reserved keyboard (for example "default_path" or "obtain_path_from_gym") to pass to the `xcarchive` parameter, to indicate that we want to upload the archive using the path coming from gym, instead amn absolute one.

**Comment by claireduf** [comment]
@acecilia 
I just open a pull request to do this

thanks for your feedback

**Pull request merged**
